### ISSUE TITLE
The "Documentation" link in crates.io is broken

### ISSUE THREAD

**Issue by cmcqueen** [pczarn/bit-matrix#2]
The Documentation link http://pczarn.github.io/cfg/bit-matrix/index.html in [bit-matrix - crates.io: Rust Package Registry](https://crates.io/crates/bit-matrix) is broken. It returns 404 not found.

I see the link in `README.md` is also broken.

**Comment by pczarn** [comment]
Fixed in v. 0.6.1

Thanks!
